version: '3'

services:
  hello_world:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: yasmf_hello_world_app
    working_dir: /app/
    ports:
      - 8080:80
    volumes:
      - ./:/app/
  